telegram:
  token: 6455629506:AAEQAFzzB0RYxpyYRZEsx2ZuLWN_dgcA_EM
  chatIDList:
    - 6266824055
    - 1247260748
  adminID: 6266824055

database:
  host: localhost
  port: 5432
  password: 1234
  user: postgres
  dbname: match_stats